-- Consumer Desk — private document storage.
--
-- One private bucket. Object keys are always "<owner uuid>/<client uuid>/<random uuid>.<ext>"
-- (or "<owner uuid>/packets/<packet uuid>.pdf"), generated by the server. The bucket is not public,
-- so there are no anonymous URLs; objects are read only through the authenticated server route.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'consumer-desk-private',
  'consumer-desk-private',
  false,
  10485760,
  array['application/pdf', 'image/png', 'image/jpeg']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy consumer_desk_owner_read on storage.objects for select to authenticated
  using (
    bucket_id = 'consumer-desk-private'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and (select public.is_owner())
  );

create policy consumer_desk_owner_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'consumer-desk-private'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and (select public.is_owner())
  );

create policy consumer_desk_owner_delete on storage.objects for delete to authenticated
  using (
    bucket_id = 'consumer-desk-private'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and (select public.is_owner())
  );
